export const AdminUserActionTypes = {
    ADMIN_SIGN_IN_START: 'ADMIN_SIGN_IN_START',
    ADMIN_SIGN_IN_SUCCESS: 'ADMIN_SIGN_IN_SUCCESS',
    ADMIN_SIGN_IN_FAILURE: 'ADMIN_SIGN_IN_FAILURE',
    SET_CURRENT_ADMIN_USER: 'SET_CURRENT_ADMIN_USER',
  };
  